### ISSUE TITLE
TypeError: Cannot read property 'context' of undefined

### ISSUE THREAD

**Issue by BetterCallSky** [unional/jest-watch-suspend#12]
Hi,

I am using jest v24.
jest config:
```
{
  "watchPlugins": [
    ["jest-watch-suspend", { "suspend-on-start": true }],
  ]
}
```

Error:
![image](https://user-images.githubusercontent.com/4478684/52271959-742b7c80-2945-11e9-924e-0a8bf11dfb29.png)

**Comment by unional** [comment]
@BetterCallSky I take a look but I don't think it is caused by this plugin. There is no `context` in the code.

I also test it with one of my other packages and it seems to be working fine.

**Comment by unional** [comment]
It seems to be working fine. Please let me know if you still experiencing the issue. Will be happy to reopen.
