### ISSUE TITLE
Save results of previous run when suspend is on

### ISSUE THREAD

**Issue by mikicho** [unional/jest-watch-suspend#56]
Hey,
First, thank you for this excellent, simple, and convenient plugin.

Currently, Jest clears the log even when suspend is on, which is less convenient when you want to look back on the test results while editing the test file:
![image](https://user-images.githubusercontent.com/11459632/187034685-0671aee3-25db-4c04-aa1c-c2315b84920a.png)

Can we prevent Jest from clearing the console when suspend is on?
Thanks

**Comment by unional** [comment]
Thanks for you kind words. 

Unfortunately, I don't think that is possible. 

Jest controls the event loop. 
This plugin suspends the test run by keeping the state inside the plugin and contribute to jest's test suite startup hooks. 

Also, if jest doesn't "clear" the result (it's actually a "re-render"), you can't interact with other watch plugins and commands, preventing most of the use cases this plugin provides. 

Cheers 🍹

**Comment by mikicho** [comment]
I understand, thanks for the reply :)
